apiVersion: v1
kind: service
metadata:
  name: postgresql
spec:
  clusterIP: None # this is will create headless service
  selector:
    app: postgresql
  ports:
    - port: 5432
      name: postgresql