apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-config

data:
  DATABASE_HOST: postgres-service
  DATABASE_PORT: "5432"
  DATABASE_NAME: fastapi
  ALGORITHM: HS256
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
  VALKEY_HOST: localhost
  VALKEY_PORT: 6379
  KAFKA_BOOTSTRAP_SERVERS: localhost:9092
  LOG_LEVEL: INFO

