apiVersion: v1
kind: service
metadata:
  name: postgres
  namespace: devsecops
spec:
  clusterIP: None # this is will create headless service
  selector:
    app: postgres
  ports:
    - port: 5432
      name: postgresql